FROM ubuntu:22.04

RUN apt-get update && apt-get install build-essential -y
RUN apt install -y pip
RUN apt install -y python2
RUN pip install openai
RUN pip install pytorch
RUN pip install chromadb
RUN pip install langchain
RUN pip install unstructured
RUN pip install tiktoken
RUN pip install matplotlib
RUN pip install selenium
RUN pip install fake_useragent
RUN pip install requests_html
RUN pip install mechanize
RUN pip install pyvirtualdisplay
RUN pip install xvfbwrapper
RUN pip install cn2an
RUN apt-get install -y xvfb