FROM ubuntu:22.04

RUN apt-get update && apt-get install build-essential -y
RUN apt install -y pip
RUN apt install -y python2
RUN pip install openai
RUN pip install chromadb
RUN pip install langchain
RUN pip install unstructured